### ISSUE TITLE
How to add energy and t1/2/3 compounds? 

### ISSUE THREAD

**Issue by inakrin** [ScreepsMods/screepsmod-market#1]
I've added them to the market.yml but they don't appear on the market list

**Comment by AlinaNova21** [comment]
Make sure you are adding them by the correct names, Ex: `XGHO2: 10`, energy is an oddball, for it use `energy: 10`

**Comment by AlinaNova21** [comment]
Resolved in slack, issue was lack of `market.yml` in Docker container. Closing.
